apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich-app
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true

  # Immich Main App (via Helm) and Value Files from Git
  sources:
  - repoURL: ghcr.io/immich-app/immich-charts
    chart: immich
    targetRevision: 0.10.3
    helm:
      valueFiles:
      - $values/argo_cd/values/immich-values.yaml
  - repoURL: https://github.com/thesmartai/CSP.git
    targetRevision: argo_cd
    ref: values
  
  destination:
    server: https://kubernetes.default.svc
    namespace: immich

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich-manifests
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true

  # Our Custom Manifests (DB Cluster, Ingress, Secrets)
  source:
    repoURL: https://github.com/thesmartai/CSP.git
    targetRevision: argo_cd
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: immich