apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: custom-headers
  namespace: traefik
spec:
  headers:
    customRequestHeaders:
      X-Permitted-Cross-Domain-Policies: master-only
      X-Version: hidden
      X-Xss-Protection: '1'
    customResponseHeaders:
      Cache-Control: no-store, no-cache
      Expect-CT: max-age=604800, enforce, report-uri='https://example.com/report'
      Permissions-Policy: >-
        accelerometer=(), camera=(), geolocation=(), gyroscope=(),
        magnetometer=(), microphone=(), payment=(), usb=()
      Referrer-Policy: no-referrer
      Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
      X-Content-Type-Options: nosniff
      X-Frame-Options: SAMEORIGIN
      content-security-policy: >-
        default-src * 'unsafe-inline' 'unsafe-eval'; script-src *
        'unsafe-inline' 'unsafe-eval' data:; connect-src * 'unsafe-inline';
        img-src * data: blob: 'unsafe-inline'; frame-src *; style-src *
        'unsafe-inline'; font-src * data:; worker-src * blob: data:; object-src
        'none';
      server: hide