apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: immich
spec:
  ingressClassName: contour
  defaultBackend:
    service:
      name: immich-server
      port:
        number: 2283
